CREATE DATABASE LETRIX;
USE LETRIX; 

CREATE TABLE login(
id_login INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
gmail VARCHAR(100) NOT NULL,
senha VARCHAR(250) NOT NULL
);

CREATE TABLE pontuaçao(
id_pontuaçao INT PRIMARY KEY AUTO_INCREMENT,
id_usuario INT NOT NULL,
data_conquista DATETIME DEFAULT CURRENT_TIMESTAMP,
pontos INT NOT NULL DEFAULT 0,
FOREIGN KEY (id_usuario) REFERENCES login(id_login)
);